site_name: EP1000 DFab
theme:
  name: material
  # see https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette
  palette:
    primary: "deep"
    accent: "indigo"
  font:
    false
    # text: "Ubuntu"
    # code: "Ubuntu Mono"
  feature:
    tabs: true
nav:
  - Home: index.md
  - Course: 
    - Fablab Safety: safety.md
    - Project Management: proj-mgmt.md
    - Web Development: web.md
    - Computer Aided Design: cad.md
    - Embedded Programming: embedded.md
    - 3D Printing: 3dprint.md
    - Laser Cutting: laser.md
  - Final Project: project.md
  - About: about.md
  - Contact: contact.md
plugins:
  - search
markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
